# Generated by Django 3.1.3 on 2020-11-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BSATTtoSATT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsatt_address', models.CharField(max_length=100)),
                ('bsatt_burn_hash', models.CharField(max_length=100)),
                ('satt_address', models.CharField(max_length=100)),
                ('satt_transaction_hash', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SATTtoBSATT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satt_address', models.CharField(max_length=100)),
                ('satt_transaction_hash', models.CharField(max_length=100)),
                ('bsatt_address', models.CharField(max_length=100)),
                ('bsatt_mint_hash', models.CharField(max_length=100)),
                ('bsatt_send_hash', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
            ],
        ),
    ]
