# Generated by Django 3.1.3 on 2020-11-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsatttosatt',
            name='bsatt_transaction_hash',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
